### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/jvm'

### ISSUE THREAD

**Issue by hufangjian** [fighting41love/cocoNLP#11]
from cocoNLP.extractor import extractor

**Comment by fighting41love** [comment]
Could you pls tell me the details of the bug? I want to reproduce the bug.
For instance, your operating system and python version.
This repo works well on python=3.6 on mac os and ubuntu.

**Comment by Cinolee** [comment]
我也遇到了这个问题，运行环境是Ubuntu16.04+python35，不过是在docker中运行的(这个影响么)

**Comment by fighting41love** [comment]
> 我也遇到了这个问题，运行环境是Ubuntu16.04+python35，不过是在docker中运行的(这个影响么)

是不是没装jvm。。。
https://github.com/FraBle/python-duckling/issues/32#issuecomment-399802149
