### ISSUE TITLE
提取人名，多个人名时只返回最后一个人名？

### ISSUE THREAD

**Issue by YUZHANG001** [fighting41love/cocoNLP#12]
from cocoNLP.extractor import extractor
ex=extractor()
text1='急寻王龙，短发，王龙，男，丢失发型短发，...如有线索，请迅速与警方联系：19909156745'
name=ex.extract_name(text1)
print(name)

output:王龙
但是源码中说返回的是['王龙','王龙']

请问这是怎么回事？

**Comment by fighting41love** [comment]
extractor.py中line 261:
`
return self.most_common(names)
`
我这里后来改为返回出现次数最多的人名，如果想要返回所有人名，可以将python site-packages中的cocoNLP/cocoNLP/extractor.py line 261改为:
`
return names
`

**Comment by YUZHANG001** [comment]
已解决 多谢！
