### ISSUE TITLE
怎么自定义人名库

### ISSUE THREAD

**Issue by 812406210** [fighting41love/cocoNLP#38]
怎么自定义人名库，然后从自定义人名库中抽取人名？希望得到解答，谢谢

**Comment by fighting41love** [comment]
> 怎么自定义人名库，然后从自定义人名库中抽取人名？希望得到解答，谢谢

可以从jieba分词配置词典的功能入手，将词、词性（人名）配置进去，进行分词、命名实体识别时，能够直接得到人名，这一步之后可以再用别的工具包走一遍，再捞一下。供参考哦。
