### ISSUE TITLE
时间提取显示比当前多了一天?

### ISSUE THREAD

**Issue by Zengpr** [fighting41love/cocoNLP#6]
4点15分钟后的番茄炒蛋
{"type": "timestamp", "timestamp": "2019-03-06 04:15:00"}
今天是3月5号

**Comment by fighting41love** [comment]
这个问题是这样的。4点15份，默认是凌晨4点15分（24小时制）， 当前时间已经过了今天的凌晨4点15分，所以默认是第二天的凌晨4点15。如果是16点15分钟后的番茄炒蛋，抽取的结果为：
`
{"type": "timestamp", "timestamp": "2019-03-05 16:15:00"}
`
如果是：下午4点15分钟后的番茄炒蛋，结果是有问题的，如下
`
{"type": "timestamp", "timestamp": "2019-03-06 16:15:00"}
`
后面我fix一下。

**Comment by Zengpr** [comment]
好的!

**Comment by fighting41love** [comment]
在新的代码里，我已更新抽取逻辑。比如4点15分钟后的番茄炒蛋，在新的cocoNLP==0.0.13中，抽取的时间为`{"type": "timestamp", "timestamp": "2019-03-05 04:15:00"}`

**Comment by fighting41love** [comment]
两个版本的代码都可以保存一下，不知道什么时候需要哪个版本呢。
