### ISSUE TITLE
很棒的库，请问可以直接提取三元组吗？

### ISSUE THREAD

**Issue by kangbrilliant** [fighting41love/cocoNLP#7]

**Comment by fighting41love** [comment]
https://github.com/liuhuanyong/EventTriplesExtraction 不知道这个是不是你想要的

**Comment by kangbrilliant** [comment]
> https://github.com/liuhuanyong/EventTriplesExtraction 不知道这个是不是你想要的

谢谢您的建议，这个我之前尝试过，但是准确率有些不尽人意。
因此想尝试一下用您的代码提取三元组，看一看是否有提升。
